initialize = ->
  mapOptions =
    center: new (google.maps.LatLng)(49.840125, 24.092779)
    zoom: 13
    mapTypeId: google.maps.MapTypeId.ROADMAP
    mapTypeControl: true
    panControl: true
    panControlOptions: position: google.maps.ControlPosition.TOP_RIGHT
    zoomControl: true
    zoomControlOptions:
      style: google.maps.ZoomControlStyle.LARGE
      position: google.maps.ControlPosition.LEFT_TOP
    streetViewControl: true
    streetViewControlOptions:
      position: google.maps.ControlPosition.LEFT_TOP

  map = new (google.maps.Map)(document.getElementById('map_canvas'), mapOptions)

  # -------------- MARKER 1
  marker1 = new (google.maps.Marker)(
    position: new (google.maps.LatLng)(49.839655, 24.031259)
    map: map
    icon: '/assets/Provesin-mark-1-active.png')

  # MARKER 1'S INFO WINDOW
  infowindow1 = new (google.maps.InfoWindow)(
    content: 'БК «Нове місто»<br />вул. Валова 3/2
м. Львів, Україна, 79008<br /><br /><a href="http://www.novemisto.com" target="_blank">БК «Нове місто»</a>')
  # End of infowindow code
  # Adding a click event to the marker
  google.maps.event.addListener marker1, 'click', ->
# Calling the open method of the infoWindow
    infowindow1.open map, marker1
  # -------- END OF 1st MARKER
  # -------------- MARKER 2
  marker2 = new (google.maps.Marker)(
    position: new (google.maps.LatLng)(49.837980, 24.104066)
    map: map
    icon: '/assets/Provesin-mark-2-active.png')
  # MARKER 2'S INFO WINDOW
  infowindow2 = new (google.maps.InfoWindow)(
    content: 'КМ «Провесінь»<br />вул. Тракт Глинянський, 152
м. Львів, Україна, 79067<br /><br /><a href="http://provesin.lviv.ua/" target="_blank">КМ «Провесінь»</a>')
  # End of infowindow code
  # Adding a click event to the marker
  google.maps.event.addListener marker2, 'click', ->
# Calling the open method of the infoWindow
    infowindow2.open map, marker2
  # -------- END OF 2nd MARKER
  # -------------- MARKER 3
  marker3 = new (google.maps.Marker)(
    position: new (google.maps.LatLng)(49.841836, 24.103552)
    map: map
    icon: '/assets/Provesin-mark-3-active.png')
  # MARKER 3'S INFO WINDOW
  infowindow3 = new (google.maps.InfoWindow)(
    content: 'КМ «Провесінь»<br />вул. Тракт Глинянський, 152
м. Львів, Україна, 79067<br /><br /><a href="http://provesin.lviv.ua/" target="_blank">КМ «Провесінь»</a>')
  # End of infowindow code
  # Adding a click event to the marker
  google.maps.event.addListener marker3, 'click', ->
# Calling the open method of the infoWindow
    infowindow3.open map, marker3
# -------- END OF 3rd MARKER

google.maps.event.addDomListener window, 'load', initialize

# ---
# generated by js2coffee 2.1.0

#initialize = ->
#  $map = $('#map_canvas')
#  lat = $map.attr 'data-lat'
#  lng = $map.attr 'data-lng'
#
#  address = $map.attr 'data-address'
#  city = $map.attr 'data-city'
#
#  myLatlng = new (google.maps.LatLng)(lat, lng)
#
#  styles = [
#    {
#      stylers: [
##        { "hue": "#ff7700" },
##        { "lightness": -2 },
##        { "gamma": 0.69 }
#      ]
#    }
#  ]
##
#  styledMap = new google.maps.StyledMapType(styles,
#    name: "Styled Map"
#  )
#
#  mapOptions =
#    zoom: 16
#    center: myLatlng
#    scrollwheel: false
#    mapTypeIds: [
#      google.maps.MapTypeId.ROADMAP
#      "map_style"
#    ]
#
#  map = new (google.maps.Map)(document.getElementById('map_canvas'), mapOptions)
#  map.mapTypes.set "map_style", styledMap
#  map.setMapTypeId "map_style"
#
#  contentString = "<div id=\"content\">" + "<div id=\"siteNotice\">" + "</div><div class=\"info-window\"><div class=\"address\"><p>"+address+"</p></div></div>" + "</div>"
#  infowindow = new (google.maps.InfoWindow)(
#    content: contentString
#
#  )
#  marker = new (google.maps.Marker)(
#    position: myLatlng
#    map: map
#    title: 'Budapest'
#    icon: '/assets/Provesin-mark-3-active.png')
#  google.maps.event.addListener marker, 'click', ->
#    infowindow.open map, marker
#
#google.maps.event.addDomListener window, 'load', initialize
#
#